baseURL: 'https://marcpabst.github.io/hugo-maps/'
languageCode: 'en-gb'
title: 'Hugo Maps Demo'

params:
  hugo-maps:
      default:
        tiles: https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=get_your_own_OpIi9ZULNHzrESv6T2vL
        height: 500px
      map_3d:
        type: remote
        style: maptiler-3d
        center: [-0.127758, 51.507351]
        wm-bounding-box: [0.499265, 0.3329205529428414, 0.5001916666666667, 0.33214313777934357]
        tilesMinZoom: 0
        tilesMaxZoom: 14
        minZoom: 4
        maxZoom: 20
        zoom: 15
        pitch: 30
        antialias: true
        markers:
          - location: [-0.127972, 51.507722, ]
            text: "Nelson's Column"
      map1:
        type: remote
        style: osm-bright
        center: [-0.127758, 51.507351]
      map2:
        type: remote
        style: toner

module:
  imports:
   - # theme
     path: "github.com/alex-shpak/hugo-book"
   - # maps
     path: "github.com/marcpabst/hugo-maps"